#!/bin/bash

set -euo pipefail

echo "You started with $# parameter(s)"

while [ "$#" -gt 0 ]; do
	echo "You now have $# parameter(s)"
	echo "The first parameter is $1"

	# shifting all parameters down by 1
	shift

done

